name: shared_map_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  http: ^0.13.5
  flutter_screenutil: ^5.8.4
  location: ^7.0.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/dark.json
    - assets/logo.png
  uses-material-design: true